/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthorTile: typeof import('./components/blog/AuthorTile.vue')['default']
    Badges: typeof import('./components/Badges.vue')['default']
    BlockQuote: typeof import('./components/BlockQuote.vue')['default']
    BlogLayoutAsideTop: typeof import('./components/blog/BlogLayoutAsideTop.vue')['default']
    BlogListings: typeof import('./components/blog/BlogListings.vue')['default']
    BlogListingTile: typeof import('./components/blog/BlogListingTile.vue')['default']
    BlogPostAuthor: typeof import('./components/blog/BlogPostAuthor.vue')['default']
    BlogPostDate: typeof import('./components/blog/BlogPostDate.vue')['default']
    BlogPostDetails: typeof import('./components/blog/BlogPostDetails.vue')['default']
    BlogPostLayoutBottom: typeof import('./components/blog/BlogPostLayoutBottom.vue')['default']
    BlogPostLayoutTop: typeof import('./components/blog/BlogPostLayoutTop.vue')['default']
    BlogPostLinkBack: typeof import('./components/blog/BlogPostLinkBack.vue')['default']
    BlogPostLinks: typeof import('./components/blog/BlogPostLinks.vue')['default']
    BlogPostTags: typeof import('./components/blog/BlogPostTags.vue')['default']
    BlogSubscribeForm: typeof import('./components/blog/BlogSubscribeForm.vue')['default']
    CategoriesNav: typeof import('./components/blog/CategoriesNav.vue')['default']
    Category: typeof import('./components/blog/Category.vue')['default']
    Contributors: typeof import('./components/Contributors.vue')['default']
    DatabaseBlock: typeof import('./components/DatabaseBlock.vue')['default']
    DatabaseSelect: typeof import('./components/DatabaseSelect.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    LanguageBlock: typeof import('./components/LanguageBlock.vue')['default']
    LanguageSelect: typeof import('./components/LanguageSelect.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    Tab: typeof import('./components/Tab.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TagIcon: typeof import('./components/blog/TagIcon.vue')['default']
    TeamMember: typeof import('./components/TeamMember.vue')['default']
  }
}
